[build]
  command = "bundle config set path vendor/bundle && bundle install --jobs=4 --retry=3 && bundle exec jekyll build"
  functions = "netlify/functions"
  environment = { RUBY_VERSION = "3.2.2", BUNDLE_FORCE_RUBY_PLATFORM = "1" }

[functions]
  directory = "netlify/functions"
